import type { DocEntry } from "./types";

export const firebaseDocs: DocEntry[] = [
  {
    id: "firebase-setup",
    title: "Setup & Initialization",
    category: "firebase",
    summary:
      "FlutterFire CLI setup, Firebase.initializeApp, and firebase_options.dart generation.",
    content: `Use **FlutterFire CLI** to configure Firebase. Run \`flutterfire configure\` to register your app, download config files, and generate \`lib/firebase_options.dart\`. Initialize Firebase in \`main.dart\` with \`Firebase.initializeApp()\`.`,
    codeSnippets: [
      {
        language: "bash",
        label: "FlutterFire CLI Setup",
        code: `# Install FlutterFire CLI
dart pub global activate flutterfire_cli

# Install Firebase CLI
npm install -g firebase-tools
firebase login

# Configure Flutter app
flutterfire configure`,
      },
      {
        language: "dart",
        label: "Firebase Initialization",
        code: `import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // auto-generated by flutterfire

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}`,
      },
    ],
    relatedWeeks: [28],
    tags: [
      "Firebase",
      "setup",
      "initialization",
      "flutterfire",
      "CLI",
      "firebase_options",
    ],
    difficulty: "beginner",
  },
  {
    id: "firebase-auth",
    title: "Firebase Authentication",
    category: "firebase",
    summary:
      "Email/Password, Google, Phone sign-in, auth state streams, and error handling.",
    content: `**firebase_auth** supports Email/Password, Google, Apple, Phone, and anonymous sign-in. Listen to auth state changes with \`authStateChanges()\` stream. Handle errors with typed \`FirebaseAuthException\` catch clauses.`,
    codeSnippets: [
      {
        language: "dart",
        label: "Email/Password Auth",
        code: `// Listen to auth state
FirebaseAuth.instance.authStateChanges().listen((User? user) {
  if (user == null) {
    print('User is signed out');
  } else {
    print('User is signed in: \${user.email}');
  }
});

// Register
Future<UserCredential> signUp(String email, String password) async {
  try {
    return await FirebaseAuth.instance.createUserWithEmailAndPassword(
      email: email,
      password: password,
    );
  } on FirebaseAuthException catch (e) {
    switch (e.code) {
      case 'weak-password':
        throw Exception('Password is too weak');
      case 'email-already-in-use':
        throw Exception('Email already registered');
      default:
        throw Exception(e.message);
    }
  }
}

// Sign In
await FirebaseAuth.instance.signInWithEmailAndPassword(
  email: email, password: password,
);

// Sign Out
await FirebaseAuth.instance.signOut();

// Password Reset
await FirebaseAuth.instance.sendPasswordResetEmail(email: email);`,
      },
      {
        language: "dart",
        label: "Google & Phone Auth",
        code: `// Google Sign-In
Future<UserCredential?> signInWithGoogle() async {
  final GoogleSignInAccount? googleUser = await GoogleSignIn().signIn();
  if (googleUser == null) return null;
  final googleAuth = await googleUser.authentication;
  final credential = GoogleAuthProvider.credential(
    accessToken: googleAuth.accessToken,
    idToken: googleAuth.idToken,
  );
  return await FirebaseAuth.instance.signInWithCredential(credential);
}

// Phone Authentication
await FirebaseAuth.instance.verifyPhoneNumber(
  phoneNumber: '+201234567890',
  verificationCompleted: (PhoneAuthCredential credential) async {
    await FirebaseAuth.instance.signInWithCredential(credential);
  },
  codeSent: (String verificationId, int? resendToken) {
    myVerificationId = verificationId;
  },
);

// Verify OTP
final credential = PhoneAuthProvider.credential(
  verificationId: myVerificationId,
  smsCode: userEnteredOTP,
);
await FirebaseAuth.instance.signInWithCredential(credential);`,
      },
    ],
    relatedWeeks: [28, 29],
    tags: [
      "firebase_auth",
      "authentication",
      "Email",
      "Google",
      "Phone",
      "sign in",
      "sign up",
      "auth state",
    ],
    difficulty: "intermediate",
  },
  {
    id: "firebase-firestore",
    title: "Cloud Firestore",
    category: "firebase",
    summary:
      "NoSQL real-time database — CRUD, queries, real-time listeners, batch writes, and transactions.",
    content: `**cloud_firestore** is a NoSQL, real-time, cloud-hosted document database organized in collections and documents. Supports CRUD operations, queries with filters, real-time listeners, batch writes, transactions, and type-safe converters.`,
    codeSnippets: [
      {
        language: "dart",
        label: "Firestore CRUD",
        code: `final db = FirebaseFirestore.instance;

// CREATE — add document (auto-generated ID)
final docRef = await db.collection('users').add({
  'name': 'Mustafa',
  'age': 25,
  'createdAt': FieldValue.serverTimestamp(),
});

// CREATE — set with known ID
await db.collection('users').doc('userId123').set({
  'name': 'Mustafa', 'age': 25,
});

// READ — get single document
final docSnap = await db.collection('users').doc('userId123').get();
if (docSnap.exists) {
  final data = docSnap.data() as Map<String, dynamic>;
  print(data['name']);
}

// UPDATE
await db.collection('users').doc('userId123').update({
  'age': 26,
  'updatedAt': FieldValue.serverTimestamp(),
});

// DELETE
await db.collection('users').doc('userId123').delete();`,
      },
      {
        language: "dart",
        label: "Queries & Real-Time Listeners",
        code: `// Queries
final query = await db.collection('users')
    .where('age', isGreaterThan: 18)
    .where('isActive', isEqualTo: true)
    .orderBy('createdAt', descending: true)
    .limit(10)
    .get();

// Real-time listener
db.collection('messages')
    .where('chatId', isEqualTo: chatId)
    .orderBy('createdAt')
    .snapshots()
    .listen((QuerySnapshot snapshot) {
  for (final change in snapshot.docChanges) {
    switch (change.type) {
      case DocumentChangeType.added:
        print('New message: \${change.doc.data()}');
      case DocumentChangeType.modified:
        print('Modified: \${change.doc.id}');
      case DocumentChangeType.removed:
        print('Removed: \${change.doc.id}');
    }
  }
});

// Batch writes
final batch = db.batch();
batch.set(db.collection('users').doc('user1'), {'name': 'Alice'});
batch.update(db.collection('users').doc('user2'), {'score': 100});
batch.delete(db.collection('users').doc('user3'));
await batch.commit();`,
      },
    ],
    relatedWeeks: [28, 29, 30],
    tags: [
      "Firestore",
      "cloud_firestore",
      "NoSQL",
      "CRUD",
      "real-time",
      "queries",
      "batch writes",
      "transactions",
    ],
    difficulty: "intermediate",
  },
  {
    id: "firebase-storage",
    title: "Firebase Storage",
    category: "firebase",
    summary:
      "File upload/download with progress tracking, download URLs, and file listing.",
    content: `**firebase_storage** stores files (images, videos, documents) with fine-grained access control. Supports upload from File/bytes, download URL retrieval, progress tracking, and file listing.`,
    codeSnippets: [
      {
        language: "dart",
        label: "Storage Upload & Download",
        code: `final storageRef = FirebaseStorage.instance.ref();

// UPLOAD — from File with progress
Future<String> uploadFile(File file, String path) async {
  final ref = storageRef.child(path);
  final uploadTask = ref.putFile(
    file,
    SettableMetadata(contentType: 'image/jpeg'),
  );
  uploadTask.snapshotEvents.listen((TaskSnapshot snap) {
    final progress = snap.bytesTransferred / snap.totalBytes;
    print('Upload: \${(progress * 100).toStringAsFixed(0)}%');
  });
  final snapshot = await uploadTask;
  return await snapshot.ref.getDownloadURL();
}

// DOWNLOAD — get URL
final downloadURL = await storageRef
    .child('avatars/userId123.jpg')
    .getDownloadURL();

// LIST files
final result = await storageRef.child('avatars').listAll();
for (final item in result.items) {
  print(item.name);
}`,
      },
    ],
    relatedWeeks: [29, 30],
    tags: [
      "firebase_storage",
      "file upload",
      "file download",
      "download URL",
      "progress",
      "storage",
    ],
    difficulty: "intermediate",
  },
  {
    id: "firebase-fcm",
    title: "Cloud Messaging (FCM)",
    category: "firebase",
    summary:
      "Push notifications for Android/iOS/Web — foreground, background, topics, and tokens.",
    content: `**firebase_messaging** handles push notifications for Android, iOS, and Web. Supports foreground/background messages, topic subscriptions, token management, and integration with **flutter_local_notifications** for local notifications.`,
    codeSnippets: [
      {
        language: "dart",
        label: "FCM Setup",
        code: `final messaging = FirebaseMessaging.instance;

// Request permission (iOS / Web)
final settings = await messaging.requestPermission(
  alert: true, badge: true, sound: true,
);

// Get FCM token
final token = await messaging.getToken();

// Foreground messages
FirebaseMessaging.onMessage.listen((RemoteMessage message) {
  print('Title: \${message.notification?.title}');
  print('Body: \${message.notification?.body}');
  print('Data: \${message.data}');
  showLocalNotification(message);
});

// Background message handler (top-level function)
@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(
  RemoteMessage message,
) async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
}
FirebaseMessaging.onBackgroundMessage(
  _firebaseMessagingBackgroundHandler,
);

// Subscribe to topic
await messaging.subscribeToTopic('news');`,
      },
    ],
    relatedWeeks: [29, 30],
    tags: [
      "FCM",
      "firebase_messaging",
      "push notifications",
      "topics",
      "tokens",
      "background handler",
    ],
    difficulty: "advanced",
  },
  {
    id: "firebase-analytics",
    title: "Firebase Analytics",
    category: "firebase",
    summary:
      "Track user behavior with custom events, user IDs, screen views, and pre-defined events.",
    content: `**firebase_analytics** tracks user behavior automatically (first_open, session_start, screen_view) and with custom events. Set user ID and properties for cross-device tracking.`,
    codeSnippets: [
      {
        language: "dart",
        label: "Analytics Events",
        code: `final analytics = FirebaseAnalytics.instance;

// Log custom event
await analytics.logEvent(
  name: 'purchase',
  parameters: {
    'item_id': 'prod_123',
    'item_name': 'Flutter Course',
    'value': 49.99,
    'currency': 'USD',
  },
);

// Set user ID
await analytics.setUserId(
  id: FirebaseAuth.instance.currentUser?.uid,
);

// Log screen view
await analytics.logScreenView(screenName: 'Home', screenClass: 'HomePage');

// Pre-defined events
await analytics.logLogin(loginMethod: 'google');
await analytics.logSearch(searchTerm: 'flutter tutorial');`,
      },
    ],
    relatedWeeks: [30],
    tags: [
      "firebase_analytics",
      "analytics",
      "events",
      "tracking",
      "user properties",
      "screen views",
    ],
    difficulty: "intermediate",
  },
  {
    id: "firebase-crashlytics",
    title: "Firebase Crashlytics",
    category: "firebase",
    summary:
      "Real-time crash reporting with Flutter error capture, custom keys, and user info.",
    content: `**firebase_crashlytics** provides real-time crash reporting. Pass all Flutter errors to Crashlytics in \`main.dart\`, set user info for context, and use custom keys and logs for debugging.`,
    codeSnippets: [
      {
        language: "dart",
        label: "Crashlytics Setup",
        code: `void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Pass all Flutter errors to Crashlytics
  FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterFatalError;

  // Pass async errors outside Flutter framework
  PlatformDispatcher.instance.onError = (error, stack) {
    FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
    return true;
  };

  runApp(const MyApp());
}

// Manual crash reporting
try {
  await riskyOperation();
} catch (e, stack) {
  FirebaseCrashlytics.instance.recordError(e, stack);
}

// Set user info
FirebaseCrashlytics.instance.setUserIdentifier(userId);
FirebaseCrashlytics.instance.setCustomKey('plan', 'premium');
FirebaseCrashlytics.instance.log('User clicked checkout');`,
      },
    ],
    relatedWeeks: [30],
    tags: [
      "Crashlytics",
      "crash reporting",
      "error tracking",
      "fatal errors",
      "debugging",
    ],
    difficulty: "intermediate",
  },
  {
    id: "firebase-remote-config",
    title: "Remote Config",
    category: "firebase",
    summary:
      "Change app behavior without publishing updates — defaults, fetch, activate, and listen.",
    content: `**firebase_remote_config** lets you change app behavior and appearance without publishing an update. Set defaults, fetch and activate configs, and listen to real-time updates.`,
    codeSnippets: [
      {
        language: "dart",
        label: "Remote Config",
        code: `final remoteConfig = FirebaseRemoteConfig.instance;

await remoteConfig.setConfigSettings(RemoteConfigSettings(
  fetchTimeout: const Duration(minutes: 1),
  minimumFetchInterval: const Duration(hours: 1),
));

await remoteConfig.setDefaults({
  'welcome_message': 'Welcome to my app!',
  'feature_dark_mode': false,
  'max_items_per_page': 20,
});

await remoteConfig.fetchAndActivate();

final welcomeMsg = remoteConfig.getString('welcome_message');
final darkMode = remoteConfig.getBool('feature_dark_mode');

// Listen to real-time updates
remoteConfig.onConfigUpdated.listen((event) async {
  await remoteConfig.activate();
  print('Config updated: \${event.updatedKeys}');
});`,
      },
    ],
    relatedWeeks: [30],
    tags: [
      "Remote Config",
      "feature flags",
      "A/B testing",
      "configuration",
      "remote configuration",
    ],
    difficulty: "intermediate",
  },
  {
    id: "firebase-security-rules",
    title: "Security Rules",
    category: "firebase",
    summary:
      "Protect Firestore and Storage with request.auth, resource.data, and validation.",
    content: `Write **Firestore** and **Storage** rules to protect your data. Use \`request.auth\` to verify authentication, \`resource.data\` to access existing data, and \`request.resource.data\` for incoming data validation.`,
    codeSnippets: [
      {
        language: "javascript",
        label: "Firestore & Storage Rules",
        code: `// firestore.rules
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /users/{userId} {
      allow read, write: if request.auth != null
        && request.auth.uid == userId;
    }
    match /posts/{postId} {
      allow read: if true;
      allow write: if request.auth != null;
      allow delete: if request.auth != null
        && request.auth.uid == resource.data.authorId;
    }
  }
}

// storage.rules
rules_version = '2';
service firebase.storage {
  match /b/{bucket}/o {
    match /avatars/{userId}/{fileName} {
      allow read: if true;
      allow write: if request.auth != null
        && request.auth.uid == userId
        && request.resource.size < 5 * 1024 * 1024
        && request.resource.contentType.matches('image/.*');
    }
  }
}`,
      },
    ],
    relatedWeeks: [28, 29, 30],
    tags: [
      "security rules",
      "Firestore rules",
      "Storage rules",
      "authorization",
      "data protection",
    ],
    difficulty: "advanced",
  },
  {
    id: "firebase-patterns",
    title: "Common Patterns",
    category: "firebase",
    summary:
      "Auth-gated routing, user document creation after sign-up, and chat message streams.",
    content: `Common Firebase patterns include **auth-gated routing** with go_router, **saving user documents** after sign-up, and **chat message streams** with real-time Firestore listeners.`,
    codeSnippets: [
      {
        language: "dart",
        label: "Auth-Gated Router & Chat Stream",
        code: `// Auth-gated routing
final GoRouter router = GoRouter(
  refreshListenable: AuthRefreshStream(
    FirebaseAuth.instance.authStateChanges(),
  ),
  redirect: (context, state) {
    final isLoggedIn = FirebaseAuth.instance.currentUser != null;
    final goingToLogin = state.matchedLocation == '/login';
    if (!isLoggedIn && !goingToLogin) return '/login';
    if (isLoggedIn && goingToLogin) return '/home';
    return null;
  },
  routes: [...],
);

// Chat message stream
Stream<List<Message>> getMessages(String chatId) {
  return _db.collection('chats').doc(chatId)
      .collection('messages')
      .orderBy('createdAt', descending: false)
      .snapshots()
      .map((snap) => snap.docs
          .map((doc) => Message.fromFirestore(doc))
          .toList());
}`,
      },
    ],
    relatedWeeks: [28, 29, 30],
    tags: [
      "patterns",
      "auth-gated",
      "routing",
      "chat",
      "streams",
      "real-time",
      "user document",
    ],
    difficulty: "advanced",
  },
];
